[package]
name = "valley-free-rs"
version = "0.1.0"
authors = ["Mingwei Zhang <mingwei@mwzhang.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

bzip2="0.4"
